# Generated by Django 5.2.5 on 2025-08-20 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_scan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
        ),
    ]
