# Generated by Django 5.2.5 on 2025-08-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_scantype_recentactivity_topuptransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartvalue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dashboardmetrics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicerate',
            name='service',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='CartValue',
        ),
        migrations.DeleteModel(
            name='DashboardMetrics',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceRate',
        ),
    ]
