# Generated by Django 5.2.5 on 2025-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_range', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
