# Generated by Django 5.2.5 on 2025-08-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='service',
            name='quantity_range',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rate',
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_quantity', models.IntegerField()),
                ('end_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='Cart.service')),
            ],
        ),
    ]
